apiVersion: v1
kind: Service
metadata:
  name: data-generator
  namespace: {{ .Release.Namespace }}
  labels:
    app: data-generator
spec:
  selector:
    app: data-generator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
